name: Build a Dockerfile using buildah and scan using prisma cloud compute
on: workflow_dispatch

env:
  IMAGE_NAME: pccdemo
  IMAGE_TAGS: latest ${{ github.sha }}
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}

jobs:
  build:
    name: Build image
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Buildah Action
      id: build_image
      uses: redhat-actions/buildah-build@v2
      with:
        image: pccdemo
        tags: ${{ github.sha }}
        oci: false
        containerfiles: |
          ./Dockerfile
          
    # Push the image to GHCR (Image Registry)
    - name: Push To GHCR
      uses: redhat-actions/push-to-registry@v2
      id: push
      with:
        image: ${{ steps.build_image.outputs.image }}
        tags: ${{ steps.build_image.outputs.tags }}
        registry: ${{ env.IMAGE_REGISTRY }}
        username: ${{ env.REGISTRY_USER }}
        password: ${{ env.REGISTRY_PASSWORD }}
        extra-args: |
          --disable-content-trust
    
    - name: Docker Pull
      env: 
        DOCKER_IMAGE: ${{ steps.push.outputs.registry-path }}
      run: |
        echo $DOCKER_IMAGE
        docker pull $DOCKER_IMAGE

    - name: Prisma Cloud image scan
      id: scan
      uses: PaloAltoNetworks/prisma-cloud-scan@v1
      with:
        pcc_console_url: ${{ secrets.PCC_CONSOLE_URL }}
        pcc_user: ${{ secrets.PCC_USER }}
        pcc_pass: ${{ secrets.PCC_PASS }}
        image_name: ${{ steps.push.outputs.registry-path }}

      # (Optional) for compatibility with GitHub's code scanning alerts
    - name: Upload SARIF file
      if: ${{ always() }} # necessary if using failure thresholds in the image scan
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: ${{ steps.scan.outputs.sarif_file }}
